version: '3.1'
services:
  python:
    image: python:3.9
    command: apt-get update -y && apt-get install -y python3-pip
    volumes:
      - .:/main
  app:
    build: 
      context: .
      dockerfile: DockerFile
    command: ["python3", "main.py"]
    ports:
      - "5000:5000"
    volumes:
      - .:/main
    working_dir: /main
    depends_on:
      - python
  
